<a href="https://colab.research.google.com/github/qwertinuiop/Linear-Algebra-58019/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Final Exam

Problem 1. Student A, Student B, and Student C have a total of Php 89 cash in their banks. Student A has 6 less than Student C. Student B has 3 times what Student C has. How much does each student have? (30 points)

In [89]:
import numpy as np

#A+B+C=89
#A+4C=89
#5C=95

A = np.array([[1,1,1],[1,0,4],[0,0,5]])
B = np.array([[89],[89],[95]])
C = np.linalg.inv(A).dot(B)

print("Student A, B, and C has Php of\n", C, "\nrespectively.")

Student A, B, and C has Php of
 [[13.]
 [57.]
 [19.]] 
respectively.


Problem 2. Solve each system: (30 points)

3x - y + z = 5

9x - 3y +3z = 15

-12x +4y -4z = -20 

####The problem cannot be solve because it has no inverse and it is a singular matrix that has a determinant value of 0.


In [94]:
import numpy as np

D = np.array([[3,-1,1], [9,-3,3], [-12,4,-4]])
E = np.array([[5], [15], [-20]])

print(D, "\n")
print(E, "\n")

#The problem cannot be solve because it has no inverse and it is a singular matrix that has a determinant value of 0.
invD = np.linalg.inv(D)
print(invD)

[[  3  -1   1]
 [  9  -3   3]
 [-12   4  -4]] 

[[  5]
 [ 15]
 [-20]] 



LinAlgError: ignored

Problem 3. Consider the matrix, (40 points)

1. Find the eigenvalue/s
2. Find the eigenvectors






In [4]:
import numpy as np
from numpy.linalg import eig

A = np.array([[8,5,-6],[-12,-9,12],[-3,-3,5]]) #matrix A
print(A)

a,b = np.linalg.eig(A) #Finding the eigenvalue/s and eigenvectors
print("The eigenvalue/s is/are:", a) #Output of eigenvalue/s
print("The eigenvectors are:", b) #Output of eigenvectors

[[  8   5  -6]
 [-12  -9  12]
 [ -3  -3   5]]
The eigenvalue/s is/are: [-1.  3.  2.]
The eigenvectors are: [[ 3.01511345e-01 -7.07106781e-01  7.07106781e-01]
 [-9.04534034e-01  7.07106781e-01  1.53837015e-15]
 [-3.01511345e-01 -2.26120075e-15  7.07106781e-01]]
