<a href="https://colab.research.google.com/github/qwertinuiop/Linear-Algebra-58019/blob/main/Linear_Transformation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

####To find the inverse of a matrix, the matrix is passed to the linalg.inv() of the NumPy module:

In [4]:
import numpy as np
A = np.array([[4,3],[-5,9]]) #creation of matrix A
print(A)
inv_A = np.linalg.inv(A)
print(inv_A)

[[ 4  3]
 [-5  9]]
[[ 0.17647059 -0.05882353]
 [ 0.09803922  0.07843137]]


In [5]:
B = np.array([[20],[26]])
print(B)

[[20]
 [26]]


In [6]:
X = np.linalg.inv(A).dot(B)
print(X)

[[2.]
 [4.]]


In [7]:
X = np.dot(inv_A,B)
print(X)

[[2.]
 [4.]]


###Exercise

In [9]:
#System of three linear equations
c = np.array([[4,3,2],[-2,2,3],[3,-5,2]])
print(c)
inv_c = np.linalg.inv(c)
print(inv_c)

[[ 4  3  2]
 [-2  2  3]
 [ 3 -5  2]]
[[ 0.15447154 -0.1300813   0.04065041]
 [ 0.10569106  0.01626016 -0.1300813 ]
 [ 0.03252033  0.23577236  0.11382114]]


In [10]:
d = np.array([[25],[-10],[-4]])
print(d)

[[ 25]
 [-10]
 [ -4]]


In [14]:
Y = np.dot(inv_c,d)
print(Y)

[[ 5.]
 [ 3.]
 [-2.]]


###Application

In [16]:
A = np.array([[20,10],[17,22]])
print(A)
inv_A = np.linalg.inv(A) #creation of inverse of matrix A
print(inv_A)

[[20 10]
 [17 22]]
[[ 0.08148148 -0.03703704]
 [-0.06296296  0.07407407]]


In [17]:
B = np.array([[350],[500]]) #creation of matrix B
print(B)

[[350]
 [500]]


In [18]:
X = np.dot(inv_A,B)
print(X)

[[10.]
 [15.]]


###To check if the answer is correct

In [20]:
B = np.dot(A,X)
print(B)

[[350.]
 [500.]]
