<a href="https://colab.research.google.com/github/qwertinuiop/Linear-Algebra-58019/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Question 1. Create a Python code that displays a square matrix whose length is 5 (10 points)


In [25]:
import numpy as np
A = np.array([[1,2,3,4,5],[5,4,3,2,1],[1,2,3,4,5],[5,4,3,2,1], [1,2,3,4,5]])
print(A)

[[1 2 3 4 5]
 [5 4 3 2 1]
 [1 2 3 4 5]
 [5 4 3 2 1]
 [1 2 3 4 5]]


Question 2. Create a Python code that displays a square matrix whose elements below the principal diagonal are zero (10 points)



In [26]:
B = np.triu(A)
print(B)

[[1 2 3 4 5]
 [0 4 3 2 1]
 [0 0 3 4 5]
 [0 0 0 2 1]
 [0 0 0 0 5]]


Question 3. Create a Python code that displays a square matrix which is symmetrical (10 points)



In [33]:
A = np.array([[1,7,7],[5,6,8],[7,3,4]])
print(A)
B = np.transpose(A)
print(B)

[[1 7 7]
 [5 6 8]
 [7 3 4]]
[[1 5 7]
 [7 6 3]
 [7 8 4]]


Question 4. What is the inverse of matrix C? Show your solution by python coding. (20 points)

In [14]:
C = np.array([[1,2,3],[2,3,3],[3,4,-2]])
print(C)
invC = np.linalg.inv(C) #inverse of matrix C
print(invC)

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]
[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


Question 5. What is the determinant of the given matrix in Question 4? Show your solution by python coding. (20 points)

In [23]:
C = np.array([[1,2,3],[2,3,3],[3,4,-2]]) #matrix C
print(C)
print(round(np.linalg.det(C))) #determinant of matrix C

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]
5


Question 6. Find the roots of the linear equations by showing its python codes (30 points)

5X1 + 4X2 + X3 = 3.4

10X1 + 9X2 + 4X3 = 8.8

10X1 + 13X2 + 15X3 = 19.2

In [16]:
D = np.array([[5,4,1],[10,9,4],[10,13,15]]) #creation of matrix D
invD = np.linalg.inv(D) #inverse of matrix D
E = np.array([[3.4],[8.8],[19.2]]) #creation of matrix E
X = np.dot(invD,E) #determining the roots
print(X)

[[0.2]
 [0.4]
 [0.8]]
