<a href="https://colab.research.google.com/github/qwertinuiop/Linear-Algebra-58019/blob/main/Practical_Lab_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Practical Lab Exam 1

In [56]:
import numpy as np
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,2],[3,4],[5,6]])
dot = np.dot(A,B)
print("a.", dot)

D = np.array([[1,2],[3,4]])
sum = D+D
print("b. ", sum)

C = np.array([[1,2,3], [4,5,6], [7,8,9]])
scaling = 2*C
print("c.", scaling)

a. [[22 28]
 [49 64]]
b.  [[2 4]
 [6 8]]
c. [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [50]:
prob2 = np.matrix([5, 3, -1])
print(prob2)
print("Type: Row Matrix")
print("Shape:", prob2.shape)
print("Dimension:", prob2.ndim)

[[ 5  3 -1]]
Type: Row Matrix
Shape: (1, 3)
Dimension: 2
