<a href="https://colab.research.google.com/github/qwertinuiop/Linear-Algebra-58019/blob/main/Python_Exercise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix and Its Operations


In [11]:
#numpy
import numpy as np
A = np.array([[-5,0],[4,1]])
B = np.array([[6,-3],[2,3]])
sum = A+B
difference1 = B-A
difference2 = A-B
print(sum)
print(difference1)
print(difference2)

[[ 1 -3]
 [ 6  4]]
[[11 -3]
 [-2  2]]
[[-11   3]
 [  2  -2]]
